# Generated by Django 5.2.7 on 2025-10-28 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='generated_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Сгенерированный пароль'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='generated_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Сгенерированное имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Создан тьютором'),
        ),
        migrations.CreateModel(
            name='TutorStudentCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_credentials', models.JSONField(verbose_name='Учетные данные ученика')),
                ('parent_credentials', models.JSONField(verbose_name='Учетные данные родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_creation_record', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_record', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='Тьютор')),
            ],
            options={
                'verbose_name': 'Создание ученика тьютором',
                'verbose_name_plural': 'Создания учеников тьютором',
                'ordering': ['-created_at'],
            },
        ),
    ]
