# Generated by Django 5.2.8 on 2025-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_normalize_parent_student_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (например: @username)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (например: @username)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (например: @username)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (например: @username)'),
        ),
    ]
