# Generated by Django 5.2.8 on 2025-11-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_parentprofile_telegram_studentprofile_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Специализация'),
        ),
    ]
