# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_optimization_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_tutor_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_parent_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_email_idx",
        ),
    ]
