# Generated by Django 4.2.7 on 2025-12-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_add_telegram_link_token_and_user_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="generated_password",
        ),
        migrations.RemoveField(
            model_name="tutorstudentcreation",
            name="parent_credentials",
        ),
        migrations.RemoveField(
            model_name="tutorstudentcreation",
            name="student_credentials",
        ),
        migrations.AddField(
            model_name="tutorstudentcreation",
            name="parent_username",
            field=models.CharField(
                default="", max_length=150, verbose_name="Имя пользователя родителя"
            ),
        ),
        migrations.AddField(
            model_name="tutorstudentcreation",
            name="student_username",
            field=models.CharField(
                default="", max_length=150, verbose_name="Имя пользователя ученика"
            ),
        ),
    ]
