# Generated by Django 4.2.7 on 2026-01-04 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_add_postgresql_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_student_tutor_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_student_parent_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="accounts_student_grade_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorstudentcreation",
            name="accounts_tutorcreation_tutor_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorstudentcreation",
            name="accounts_tutorcreation_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorstudentcreation",
            name="accounts_tutorcreation_parent_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorstudentcreation",
            name="accounts_tutorcreation_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_user_username_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_user_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_user_telegram_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_user_role_active_idx",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="accuracy_percentage",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Точность (%)",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="goal",
            field=models.TextField(
                blank=True,
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Цель обучения",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ],
                help_text="Student grade (1-12)",
                null=True,
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "parent"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Родитель",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="progress_percentage",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Прогресс (%)",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "tutor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutored_students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Тьютор",
            ),
        ),
        migrations.AlterField(
            model_name="telegramlinktoken",
            name="token",
            field=models.CharField(
                db_index=True, max_length=256, unique=True, verbose_name="Токен"
            ),
        ),
    ]
