# Generated by Django 4.2.7 on 2026-01-04 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_fix_studentprofile_grade_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'role': 'parent'},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children_students',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Родитель'
            ),
        ),
    ]
