# Generated by Django 4.2.7 on 2026-01-04 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_studentprofile_parent_on_delete"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE accounts_studentprofile
                DROP CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id;

                ALTER TABLE accounts_studentprofile
                ADD CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id
                FOREIGN KEY (parent_id) REFERENCES accounts_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE accounts_studentprofile
                DROP CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id;

                ALTER TABLE accounts_studentprofile
                ADD CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id
                FOREIGN KEY (parent_id) REFERENCES accounts_user(id) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
