# Generated by Django 4.2.7 on 2026-01-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_add_token_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("teacher", "Преподаватель"),
                    ("tutor", "Тьютор"),
                    ("parent", "Родитель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
