# Generated by Django 4.2.7 on 2026-01-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_user_password"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE accounts_studentprofile
                DROP CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id;

                ALTER TABLE accounts_studentprofile
                ADD CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id
                FOREIGN KEY (parent_id) REFERENCES accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE accounts_studentprofile
                DROP CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id;

                ALTER TABLE accounts_studentprofile
                ADD CONSTRAINT accounts_studentprofile_parent_id_7866a2ef_fk_accounts_user_id
                FOREIGN KEY (parent_id) REFERENCES accounts_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
