# Generated by Django 4.2.7 on 2026-01-11 00:00

from django.db import migrations


def sync_role_to_is_staff(apps, schema_editor):
    """Синхронизировать role='admin' с is_staff=True и is_superuser=True"""
    User = apps.get_model('accounts', 'User')

    # Обновить всех админов с неправильными флагами
    admin_users = User.objects.filter(role='admin').exclude(is_staff=True, is_superuser=True)
    if admin_users.exists():
        count = admin_users.update(is_staff=True, is_superuser=True)
        print(f"✓ Synchronized {count} admin users (role='admin' -> is_staff=True, is_superuser=True)")


def reverse_sync(apps, schema_editor):
    """Обратная миграция - НЕ делать ничего"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_fix_parent_cascade_to_set_null"),
    ]

    operations = [
        migrations.RunPython(sync_role_to_is_staff, reverse_sync),
    ]
