# Generated by Django 5.2.7 on 2025-10-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('student_progress', 'Прогресс студента'), ('assignment_completion', 'Выполнение заданий'), ('material_study', 'Изучение материалов'), ('attendance', 'Посещаемость'), ('engagement', 'Вовлеченность'), ('performance', 'Успеваемость')], max_length=30, verbose_name='Тип метрики')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_data', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Аналитические данные',
                'verbose_name_plural': 'Аналитические данные',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('student_progress', 'Прогресс студента'), ('class_performance', 'Успеваемость класса'), ('subject_analysis', 'Анализ по предмету'), ('weekly_summary', 'Еженедельный отчет'), ('monthly_summary', 'Месячный отчет'), ('custom', 'Пользовательский отчет')], default='custom', max_length=30, verbose_name='Тип отчета')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сгенерирован'), ('sent', 'Отправлен'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('content', models.JSONField(default=dict, verbose_name='Содержание отчета')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/files/', verbose_name='Файл отчета')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Автоматически генерируемый')),
                ('generation_frequency', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, verbose_name='Частота генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('target_parents', models.ManyToManyField(blank=True, related_name='reports_about_children', to=settings.AUTH_USER_MODEL, verbose_name='Целевые родители')),
                ('target_students', models.ManyToManyField(blank=True, related_name='reports_about_me', to=settings.AUTH_USER_MODEL, verbose_name='Целевые студенты')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('student_progress', 'Прогресс студента'), ('class_performance', 'Успеваемость класса'), ('subject_analysis', 'Анализ по предмету'), ('weekly_summary', 'Еженедельный отчет'), ('monthly_summary', 'Месячный отчет'), ('custom', 'Пользовательский отчет')], max_length=30, verbose_name='Тип отчета')),
                ('template_content', models.JSONField(default=dict, verbose_name='Содержание шаблона')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, verbose_name='Частота')),
                ('day_of_week', models.PositiveIntegerField(blank=True, choices=[(1, 'День 1'), (2, 'День 2'), (3, 'День 3'), (4, 'День 4'), (5, 'День 5'), (6, 'День 6'), (7, 'День 7')], null=True, verbose_name='День недели')),
                ('day_of_month', models.PositiveIntegerField(blank=True, choices=[(1, 'День 1'), (2, 'День 2'), (3, 'День 3'), (4, 'День 4'), (5, 'День 5'), (6, 'День 6'), (7, 'День 7'), (8, 'День 8'), (9, 'День 9'), (10, 'День 10'), (11, 'День 11'), (12, 'День 12'), (13, 'День 13'), (14, 'День 14'), (15, 'День 15'), (16, 'День 16'), (17, 'День 17'), (18, 'День 18'), (19, 'День 19'), (20, 'День 20'), (21, 'День 21'), (22, 'День 22'), (23, 'День 23'), (24, 'День 24'), (25, 'День 25'), (26, 'День 26'), (27, 'День 27'), (28, 'День 28'), (29, 'День 29'), (30, 'День 30'), (31, 'День 31')], null=True, verbose_name='День месяца')),
                ('time', models.TimeField(verbose_name='Время генерации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Последняя генерация')),
                ('next_generation', models.DateTimeField(blank=True, null=True, verbose_name='Следующая генерация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='Шаблон отчета')),
            ],
            options={
                'verbose_name': 'Расписание отчетов',
                'verbose_name_plural': 'Расписания отчетов',
                'ordering': ['next_generation'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитан')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='reports.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Получатель отчета',
                'verbose_name_plural': 'Получатели отчетов',
                'unique_together': {('report', 'recipient')},
            },
        ),
    ]
