# Generated by Django 5.2.7 on 2025-10-26 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('report_type', models.CharField(choices=[('progress', 'Отчет о прогрессе'), ('behavior', 'Отчет о поведении'), ('achievement', 'Отчет о достижениях'), ('attendance', 'Отчет о посещаемости'), ('performance', 'Отчет об успеваемости'), ('custom', 'Пользовательский отчет')], default='progress', max_length=20, verbose_name='Тип отчета')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('read', 'Прочитан'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('content', models.JSONField(default=dict, verbose_name='Содержание отчета')),
                ('overall_grade', models.CharField(blank=True, max_length=10, verbose_name='Общая оценка')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент прогресса')),
                ('attendance_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент посещаемости')),
                ('behavior_rating', models.PositiveIntegerField(choices=[(1, 'Оценка 1'), (2, 'Оценка 2'), (3, 'Оценка 3'), (4, 'Оценка 4'), (5, 'Оценка 5'), (6, 'Оценка 6'), (7, 'Оценка 7'), (8, 'Оценка 8'), (9, 'Оценка 9'), (10, 'Оценка 10')], default=5, verbose_name='Оценка поведения')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('concerns', models.TextField(blank=True, verbose_name='Обеспокоенности')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='student_reports/', verbose_name='Приложение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reports', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_student_reports', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Отчет о студенте',
                'verbose_name_plural': 'Отчеты о студентах',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student', 'period_start', 'period_end')},
            },
        ),
    ]
