# Generated by Django 5.2.8 on 2025-11-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_studentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('title', models.CharField(default='Еженедельный отчет', max_length=200, verbose_name='Название')),
                ('summary', models.TextField(verbose_name='Общее резюме')),
                ('academic_progress', models.TextField(blank=True, verbose_name='Академический прогресс')),
                ('performance_notes', models.TextField(blank=True, verbose_name='Заметки об успеваемости')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('concerns', models.TextField(blank=True, verbose_name='Обеспокоенности')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('assignments_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено заданий')),
                ('assignments_total', models.PositiveIntegerField(default=0, verbose_name='Всего заданий')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средний балл')),
                ('attendance_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент посещаемости')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('read', 'Прочитан'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='teacher_reports/', verbose_name='Приложение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject_id', models.IntegerField(verbose_name='Предмет ID')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_teacher_reports', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_teacher_reports', to=settings.AUTH_USER_MODEL, verbose_name='Тьютор')),
            ],
            options={
                'verbose_name': 'Еженедельный отчет преподавателя',
                'verbose_name_plural': 'Еженедельные отчеты преподавателя',
                'ordering': ['-week_start', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'student', '-week_start'], name='reports_tea_teacher_4310d3_idx'), models.Index(fields=['tutor', 'student', '-week_start'], name='reports_tea_tutor_i_a49cc1_idx')],
                'unique_together': {('teacher', 'student', 'subject_id', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TutorWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('title', models.CharField(default='Еженедельный отчет', max_length=200, verbose_name='Название')),
                ('summary', models.TextField(verbose_name='Общее резюме')),
                ('academic_progress', models.TextField(blank=True, verbose_name='Академический прогресс')),
                ('behavior_notes', models.TextField(blank=True, verbose_name='Заметки о поведении')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('concerns', models.TextField(blank=True, verbose_name='Обеспокоенности')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('attendance_days', models.PositiveIntegerField(default=0, verbose_name='Дней посещения')),
                ('total_days', models.PositiveIntegerField(default=7, verbose_name='Всего дней')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент прогресса')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('read', 'Прочитан'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tutor_reports/', verbose_name='Приложение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_tutor_reports', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_tutor_reports', to=settings.AUTH_USER_MODEL, verbose_name='Тьютор')),
            ],
            options={
                'verbose_name': 'Еженедельный отчет тьютора',
                'verbose_name_plural': 'Еженедельные отчеты тьютора',
                'ordering': ['-week_start', '-created_at'],
                'indexes': [models.Index(fields=['tutor', 'student', '-week_start'], name='reports_tut_tutor_i_d32ebf_idx'), models.Index(fields=['parent', '-week_start'], name='reports_tut_parent__5ea2b7_idx')],
                'unique_together': {('tutor', 'student', 'week_start')},
            },
        ),
    ]
