# Generated by Django 5.2.8 on 2025-11-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_teacherweeklyreport_tutorweeklyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherweeklyreport',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_teacher_reports', to=settings.AUTH_USER_MODEL, verbose_name='Тьютор'),
        ),
        migrations.AlterField(
            model_name='tutorweeklyreport',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tutor_reports', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
    ]
