# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0013_merge"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportScheduleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial (some recipients failed)"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("successful_sends", models.PositiveIntegerField(default=0)),
                ("failed_sends", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Report schedule execution",
                "verbose_name_plural": "Report schedule executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportScheduleRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(default=True, verbose_name="Is subscribed"),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Unsubscribe token",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Unsubscribed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report schedule recipient",
                "verbose_name_plural": "Report schedule recipients",
            },
        ),
        migrations.AlterModelOptions(
            name="reportschedule",
            options={
                "ordering": ["next_scheduled", "next_generation", "-created_at"],
                "verbose_name": "Report schedule",
                "verbose_name_plural": "Report schedules",
            },
        ),
        migrations.RemoveIndex(
            model_name="analyticsdata",
            name="analytics_data_student_metric_idx",
        ),
        migrations.RemoveIndex(
            model_name="analyticsdata",
            name="analytics_data_student_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentreport",
            name="student_report_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentreport",
            name="student_report_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentreport",
            name="student_report_teacher_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentreport",
            name="student_report_student_period_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_teacher_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_week_start_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_teacher_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_teacher_subject_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_tutor_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="teacherweeklyreport",
            name="teacher_report_teacher_week_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorweeklyreport",
            name="tutor_report_tutor_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorweeklyreport",
            name="tutor_report_week_start_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorweeklyreport",
            name="tutor_report_tutor_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorweeklyreport",
            name="tutor_report_tutor_week_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorweeklyreport",
            name="tutor_report_student_week_idx",
        ),
        migrations.RenameIndex(
            model_name="customreport",
            new_name="reports_cus_created_455aa4_idx",
            old_name="reports_cus_created_98a7e8_idx",
        ),
        migrations.RenameIndex(
            model_name="customreport",
            new_name="reports_cus_is_shar_c01c3e_idx",
            old_name="reports_cus_is_shar_7f4c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="customreportexecution",
            new_name="reports_cus_report__91c9bd_idx",
            old_name="reports_cus_report__3f2c1e_idx",
        ),
        migrations.RenameIndex(
            model_name="customreportexecution",
            new_name="reports_cus_execute_b27ee1_idx",
            old_name="reports_cus_execute_4a5b6d_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccessauditlog",
            new_name="reports_rep_report__e99542_idx",
            old_name="reports_rep_report_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccessauditlog",
            new_name="reports_rep_accesse_7a4eef_idx",
            old_name="reports_rep_accesse_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccessauditlog",
            new_name="reports_rep_access__3b67a0_idx",
            old_name="reports_rep_access__g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccessauditlog",
            new_name="reports_rep_access__41a8fb_idx",
            old_name="reports_rep_access_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccessauditlog",
            new_name="reports_rep_ip_addr_dfc3e7_idx",
            old_name="reports_rep_ip_addr_m3n4o5_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccesstoken",
            new_name="reports_rep_token_82bebc_idx",
            old_name="reports_rep_token_p6q7r8_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccesstoken",
            new_name="reports_rep_report__c0a453_idx",
            old_name="reports_rep_report_s9t0u1_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccesstoken",
            new_name="reports_rep_created_f2df78_idx",
            old_name="reports_rep_created_v2w3x4_idx",
        ),
        migrations.RenameIndex(
            model_name="reportaccesstoken",
            new_name="reports_rep_expires_044e4f_idx",
            old_name="reports_rep_expires_y5z6a7_idx",
        ),
        migrations.RenameIndex(
            model_name="reportsharing",
            new_name="reports_rep_report__6ac6e0_idx",
            old_name="reports_rep_report_8f2c4a_idx",
        ),
        migrations.RenameIndex(
            model_name="reportsharing",
            new_name="reports_rep_shared__c56581_idx",
            old_name="reports_rep_shared_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="reportsharing",
            new_name="reports_rep_share_t_b4cd4d_idx",
            old_name="reports_rep_share__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="reportsharing",
            new_name="reports_rep_expires_f516c5_idx",
            old_name="reports_rep_expires_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="reporttemplate",
            new_name="reports_rep_type_a5ec0b_idx",
            old_name="reports_rep_type_i_idx",
        ),
        migrations.RenameIndex(
            model_name="reporttemplate",
            new_name="reports_rep_created_170369_idx",
            old_name="reports_rep_created_idx",
        ),
        migrations.RenameIndex(
            model_name="reporttemplate",
            new_name="reports_rep_parent__a50f99_idx",
            old_name="reports_rep_parent_idx",
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_report_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="export_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("xlsx", "Excel"), ("pdf", "PDF")],
                default="csv",
                max_length=10,
                verbose_name="Export format",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="last_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last sent at"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Schedule name"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="next_scheduled",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Next scheduled at"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student_report", "Student Report"),
                    ("tutor_weekly_report", "Tutor Weekly Report"),
                    ("teacher_weekly_report", "Teacher Weekly Report"),
                ],
                max_length=30,
                verbose_name="Report type",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="day_of_month",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18"),
                    (19, "19"),
                    (20, "20"),
                    (21, "21"),
                    (22, "22"),
                    (23, "23"),
                    (24, "24"),
                    (25, "25"),
                    (26, "26"),
                    (27, "27"),
                    (28, "28"),
                    (29, "29"),
                    (30, "30"),
                    (31, "31"),
                ],
                null=True,
                verbose_name="Day of month (1-31)",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="day_of_week",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                null=True,
                verbose_name="Day of week (1=Monday)",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                max_length=20,
                verbose_name="Delivery frequency",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="last_generated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last generated at"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="next_generation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Next generation (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="reports.reporttemplate",
                verbose_name="Report template",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="time",
            field=models.TimeField(
                default="09:00", verbose_name="Delivery time (HH:MM)"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active", "next_scheduled"],
                name="reports_rep_is_acti_2a0809_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="reports_rep_created_fc1e79_idx",
            ),
        ),
        migrations.AddField(
            model_name="reportschedulerecipient",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportschedulerecipient",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_entries",
                to="reports.reportschedule",
            ),
        ),
        migrations.AddField(
            model_name="reportscheduleexecution",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="reports.reportschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedulerecipient",
            index=models.Index(
                fields=["schedule", "is_subscribed"],
                name="reports_rep_schedul_840a8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedulerecipient",
            index=models.Index(
                fields=["recipient", "is_subscribed"],
                name="reports_rep_recipie_e3295b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportschedulerecipient",
            unique_together={("schedule", "recipient")},
        ),
        migrations.AddIndex(
            model_name="reportscheduleexecution",
            index=models.Index(
                fields=["schedule", "-started_at"],
                name="reports_rep_schedul_65c16d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportscheduleexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="reports_rep_status_638889_idx"
            ),
        ),
    ]
