# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0035_alter_subjectenrollment_unique_together_and_more"),
        ("reports", "0014_reportscheduleexecution_reportschedulerecipient_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teacherweeklyreport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teacherweeklyreport",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_weekly_reports",
                to="materials.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherweeklyreport",
            unique_together={("teacher", "student", "subject", "week_start")},
        ),
        migrations.RemoveField(
            model_name="teacherweeklyreport",
            name="subject_id",
        ),
    ]
