# Generated by Django 5.2.7 on 2025-10-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('assignment_new', 'Новое задание'), ('assignment_due', 'Срок сдачи задания'), ('assignment_graded', 'Задание оценено'), ('material_new', 'Новый материал'), ('message_new', 'Новое сообщение'), ('report_ready', 'Отчет готов'), ('payment_success', 'Платеж успешен'), ('payment_failed', 'Платеж не прошел'), ('system', 'Системное уведомление'), ('reminder', 'Напоминание')], max_length=30, verbose_name='Тип уведомления')),
                ('title_template', models.CharField(max_length=200, verbose_name='Шаблон заголовка')),
                ('message_template', models.TextField(verbose_name='Шаблон сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('type', models.CharField(choices=[('assignment_new', 'Новое задание'), ('assignment_due', 'Срок сдачи задания'), ('assignment_graded', 'Задание оценено'), ('material_new', 'Новый материал'), ('message_new', 'Новое сообщение'), ('report_ready', 'Отчет готов'), ('payment_success', 'Платеж успешен'), ('payment_failed', 'Платеж не прошел'), ('system', 'Системное уведомление'), ('reminder', 'Напоминание')], default='system', max_length=30, verbose_name='Тип уведомления')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('in_app', 'В приложении')], max_length=20, verbose_name='Канал доставки')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки отправки')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Максимум попыток')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Запись очереди уведомлений',
                'verbose_name_plural': 'Очередь уведомлений',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_notifications', models.BooleanField(default=True, verbose_name='Уведомления о заданиях')),
                ('material_notifications', models.BooleanField(default=True, verbose_name='Уведомления о материалах')),
                ('message_notifications', models.BooleanField(default=True, verbose_name='Уведомления о сообщениях')),
                ('report_notifications', models.BooleanField(default=True, verbose_name='Уведомления об отчетах')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='Уведомления о платежах')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS уведомления')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Конец тихих часов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
