# Generated by Django 5.2.8 on 2025-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_add_invoice_notification_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment_new", "Новое задание"),
                    ("assignment_due", "Срок сдачи задания"),
                    ("assignment_graded", "Задание оценено"),
                    ("material_new", "Новый материал"),
                    ("message_new", "Новое сообщение"),
                    ("report_ready", "Отчет готов"),
                    ("payment_success", "Платеж успешен"),
                    ("payment_failed", "Платеж не прошел"),
                    ("system", "Системное уведомление"),
                    ("reminder", "Напоминание"),
                    ("student_created", "Ученик создан"),
                    ("subject_assigned", "Предмет назначен"),
                    ("material_published", "Материал опубликован"),
                    ("homework_submitted", "Домашнее задание отправлено"),
                    ("payment_processed", "Платеж обработан"),
                    ("invoice_sent", "Счет выставлен"),
                    ("invoice_paid", "Счет оплачен"),
                    ("invoice_overdue", "Счет просрочен"),
                    ("invoice_viewed", "Счет просмотрен"),
                ],
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
