# Generated by Django 4.2.7 on 2025-12-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_alter_notificationtemplate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("all_students", "Все студенты"),
                            ("all_teachers", "Все преподаватели"),
                            ("all_tutors", "Все тьюторы"),
                            ("all_parents", "Все родители"),
                            ("by_subject", "По предмету"),
                            ("by_tutor", "По тьютору"),
                            ("by_teacher", "По учителю"),
                            ("custom", "Кастомная группа"),
                        ],
                        max_length=20,
                        verbose_name="Целевая группа",
                    ),
                ),
                (
                    "target_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Фильтры: {subject_id, tutor_id, teacher_id, user_ids}",
                        verbose_name="Фильтр получателей",
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=1000, verbose_name="Сообщение"),
                ),
                (
                    "recipient_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество получателей"
                    ),
                ),
                (
                    "sent_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество отправленных"
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="Количество неудачных"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("scheduled", "Запланирована"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлена"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланирована на"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлена"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Массовая рассылка",
                "verbose_name_plural": "Массовые рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлено в Telegram"
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID сообщения в Telegram",
                    ),
                ),
                (
                    "telegram_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ошибка отправки в Telegram"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.broadcast",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
                "indexes": [
                    models.Index(
                        fields=["broadcast", "telegram_sent"],
                        name="notificatio_broadca_2cf2a0_idx",
                    ),
                    models.Index(
                        fields=["recipient", "broadcast"],
                        name="notificatio_recipie_6365a1_idx",
                    ),
                ],
                "unique_together": {("broadcast", "recipient")},
            },
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="notificatio_created_444a5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(
                fields=["status", "scheduled_at"], name="notificatio_status_ca8ad6_idx"
            ),
        ),
    ]
