# Generated by Django 4.2.7 on 2025-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_notification_notif_user_read_time_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="feedback_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления о фидбэке на материалы"
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="parent_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Уведомлять родителей о фидбэке"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment_new", "Новое задание"),
                    ("assignment_due", "Срок сдачи задания"),
                    ("assignment_graded", "Задание оценено"),
                    ("material_new", "Новый материал"),
                    ("message_new", "Новое сообщение"),
                    ("mention", "Упоминание в сообщении"),
                    ("report_ready", "Отчет готов"),
                    ("payment_success", "Платеж успешен"),
                    ("payment_failed", "Платеж не прошел"),
                    ("system", "Системное уведомление"),
                    ("reminder", "Напоминание"),
                    ("event_new", "Новое событие"),
                    ("event_reminder", "Напоминание о событии"),
                    ("forum_new_post", "Новый пост на форуме"),
                    ("forum_reply", "Ответ на форуме"),
                    ("student_created", "Ученик создан"),
                    ("subject_assigned", "Предмет назначен"),
                    ("material_published", "Материал опубликован"),
                    ("homework_submitted", "Домашнее задание отправлено"),
                    ("payment_processed", "Платеж обработан"),
                    ("invoice_sent", "Счет выставлен"),
                    ("invoice_paid", "Счет оплачен"),
                    ("invoice_overdue", "Счет просрочен"),
                    ("invoice_viewed", "Счет просмотрен"),
                    ("material_feedback", "Фидбэк на материал получен"),
                ],
                default="system",
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment_new", "Новое задание"),
                    ("assignment_due", "Срок сдачи задания"),
                    ("assignment_graded", "Задание оценено"),
                    ("material_new", "Новый материал"),
                    ("message_new", "Новое сообщение"),
                    ("mention", "Упоминание в сообщении"),
                    ("report_ready", "Отчет готов"),
                    ("payment_success", "Платеж успешен"),
                    ("payment_failed", "Платеж не прошел"),
                    ("system", "Системное уведомление"),
                    ("reminder", "Напоминание"),
                    ("event_new", "Новое событие"),
                    ("event_reminder", "Напоминание о событии"),
                    ("forum_new_post", "Новый пост на форуме"),
                    ("forum_reply", "Ответ на форуме"),
                    ("student_created", "Ученик создан"),
                    ("subject_assigned", "Предмет назначен"),
                    ("material_published", "Материал опубликован"),
                    ("homework_submitted", "Домашнее задание отправлено"),
                    ("payment_processed", "Платеж обработан"),
                    ("invoice_sent", "Счет выставлен"),
                    ("invoice_paid", "Счет оплачен"),
                    ("invoice_overdue", "Счет просрочен"),
                    ("invoice_viewed", "Счет просмотрен"),
                    ("material_feedback", "Фидбэк на материал получен"),
                ],
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notif_user_read_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["is_read"], name="notif_is_read_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "-created_at"], name="notif_type_time_idx"
            ),
        ),
    ]
