# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0015_merge"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_user_read_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_is_read_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_type_time_idx",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_user_id_f0e72c_idx",
            old_name="notificati_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_token_1a2c49_idx",
            old_name="notificati_token_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_2c5a1d_idx",
            old_name="notif_archive_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_b9dbed_idx",
            old_name="notif_archive_simple_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_schedul_150031_idx",
            old_name="notif_schedule_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_cdd4b8_idx",
            old_name="notif_user_schedule_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationclick",
            new_name="notificatio_notific_407c83_idx",
            old_name="notifications_notificationclick_notification_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationclick",
            new_name="notificatio_user_id_a5baeb_idx",
            old_name="notifications_notificationclick_user_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationclick",
            new_name="notificatio_notific_243102_idx",
            old_name="notifications_notificationclick_notification_user_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationclick",
            new_name="notificatio_created_95ea28_idx",
            old_name="notifications_notificationclick_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationunsubscribe",
            new_name="notificatio_user_id_08f838_idx",
            old_name="notifications_notif_user_id_unsubscr_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationunsubscribe",
            new_name="notificatio_channel_998872_idx",
            old_name="notifications_notif_channel_unsubsc_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationunsubscribe",
            new_name="notificatio_unsubsc_2a0735_idx",
            old_name="notifications_notif_unsubscribed_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationunsubscribe",
            new_name="notificatio_user_id_d1a280_idx",
            old_name="notifications_notif_user_id_resubsc_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdeliverylog",
            new_name="notificatio_notific_2af141_idx",
            old_name="notificati_notifi_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdeliverylog",
            new_name="notificatio_user_id_565823_idx",
            old_name="notificati_user_i_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdeliverylog",
            new_name="notificatio_notific_11d204_idx",
            old_name="notificati_notifi_6a4c_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdeliverylog",
            new_name="notificatio_success_2a2e73_idx",
            old_name="notificati_success_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdeliverylog",
            new_name="notificatio_sent_at_f1e455_idx",
            old_name="notificati_sent_at_idx",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="feedback_notifications",
        ),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="parent_notifications",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment_new", "Новое задание"),
                    ("assignment_due", "Срок сдачи задания"),
                    ("assignment_graded", "Задание оценено"),
                    ("material_new", "Новый материал"),
                    ("message_new", "Новое сообщение"),
                    ("report_ready", "Отчет готов"),
                    ("payment_success", "Платеж успешен"),
                    ("payment_failed", "Платеж не прошел"),
                    ("system", "Системное уведомление"),
                    ("reminder", "Напоминание"),
                    ("student_created", "Ученик создан"),
                    ("subject_assigned", "Предмет назначен"),
                    ("material_published", "Материал опубликован"),
                    ("homework_submitted", "Домашнее задание отправлено"),
                    ("payment_processed", "Платеж обработан"),
                    ("invoice_sent", "Счет выставлен"),
                    ("invoice_paid", "Счет оплачен"),
                    ("invoice_overdue", "Счет просрочен"),
                    ("invoice_viewed", "Счет просмотрен"),
                ],
                default="system",
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment_new", "Новое задание"),
                    ("assignment_due", "Срок сдачи задания"),
                    ("assignment_graded", "Задание оценено"),
                    ("material_new", "Новый материал"),
                    ("message_new", "Новое сообщение"),
                    ("report_ready", "Отчет готов"),
                    ("payment_success", "Платеж успешен"),
                    ("payment_failed", "Платеж не прошел"),
                    ("system", "Системное уведомление"),
                    ("reminder", "Напоминание"),
                    ("student_created", "Ученик создан"),
                    ("subject_assigned", "Предмет назначен"),
                    ("material_published", "Материал опубликован"),
                    ("homework_submitted", "Домашнее задание отправлено"),
                    ("payment_processed", "Платеж обработан"),
                    ("invoice_sent", "Счет выставлен"),
                    ("invoice_paid", "Счет оплачен"),
                    ("invoice_overdue", "Счет просрочен"),
                    ("invoice_viewed", "Счет просмотрен"),
                ],
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
