# Generated by Django 4.2.7 on 2025-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0016_remove_notification_notif_user_read_time_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="scope",
            field=models.CharField(
                choices=[
                    ("user", "User-specific"),
                    ("system", "System-wide"),
                    ("admin", "Admin-only"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="Scope (user/system/admin)",
            ),
        ),
    ]
