# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0017_add_notification_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.TextField(
                help_text="Device token for push notifications",
                unique=True,
                verbose_name="Device Token",
            ),
        ),
        migrations.AlterField(
            model_name="pushdeliverylog",
            name="error_code",
            field=models.CharField(
                blank=True,
                help_text="SMS error code",
                max_length=50,
                verbose_name="Код ошибки",
            ),
        ),
        migrations.AlterField(
            model_name="pushdeliverylog",
            name="fcm_message_id",
            field=models.CharField(
                blank=True,
                help_text="ID сообщения от провайдера",
                max_length=255,
                verbose_name="Message ID",
            ),
        ),
    ]
