rules:
  - id: secure-password-hashing
    pattern-either:
      - patterns:
          - pattern: |
              from django.contrib.auth.hashers import make_password
              ...
              make_password(...)
          - metavariable-pattern:
              metavariable: $VAR
              patterns:
                - pattern: $VAR
          - focusmetavariable: $VAR
    message: "Using Django password hashing utilities correctly"
    languages: [python]
    severity: INFO

  - id: sql-injection-risk
    patterns:
      - pattern-either:
          - pattern: |
              ...
              execute($QUERY)
              ...
          - pattern: |
              ...
              query($QUERY)
              ...
    message: "Potential SQL injection vulnerability"
    languages: [python]
    severity: WARNING

  - id: hardcoded-secrets
    patterns:
      - pattern-either:
          - pattern: "SECRET_KEY = '...'"
          - pattern: 'SECRET_KEY = "..."'
          - pattern: "password = '...'"
          - pattern: 'password = "..."'
          - pattern: "API_KEY = '...'"
          - pattern: 'API_KEY = "..."'
    message: "Potential hardcoded secret found"
    languages: [python]
    severity: CRITICAL

  - id: eval-usage
    patterns:
      - pattern-either:
          - pattern: "eval(...)"
          - pattern: "exec(...)"
          - pattern: "pickle.loads(...)"
    message: "Use of dangerous eval/exec/pickle functions"
    languages: [python]
    severity: CRITICAL

  - id: missing-csrf-protection
    patterns:
      - pattern: |
          @csrf_exempt
          def ...(...):
              ...
    message: "CSRF protection disabled - verify this is intentional"
    languages: [python]
    severity: WARNING

  - id: insecure-deserialization
    patterns:
      - pattern-either:
          - pattern: "yaml.load(...)"
          - pattern: "pickle.loads(...)"
          - pattern: "json.loads(untrusted_data)"
    message: "Insecure deserialization detected"
    languages: [python]
    severity: CRITICAL

  - id: shell-injection
    patterns:
      - pattern-either:
          - pattern: "shell=True"
          - pattern: "os.system(...)"
          - pattern: "subprocess.call(..., shell=True)"
    message: "Potential shell injection vulnerability"
    languages: [python]
    severity: HIGH

  - id: no-jwt-validation
    patterns:
      - pattern-either:
          - pattern: "jwt.decode(..., options={'verify_signature': False})"
          - pattern: "decode(..., options={'verify_signature': False})"
    message: "JWT signature verification disabled"
    languages: [python]
    severity: CRITICAL

  - id: insecure-random
    patterns:
      - pattern-either:
          - pattern: "random.choice(...)"
          - pattern: "random.random(...)"
          - pattern: "Math.random()"
    message: "Insecure random number generation for security context"
    languages: [python, javascript]
    severity: HIGH

  - id: missing-authentication
    patterns:
      - pattern-either:
          - pattern: |
              @api_view(['GET', 'POST'])
              def api_endpoint(...):
                  ...
          - pattern: |
              class MyViewSet(ViewSet):
                  def list(self, request):
                      ...
    message: "API endpoint may be missing authentication"
    languages: [python]
    severity: MEDIUM
