# Generated by Django 4.2.7 on 2025-11-29 19:09
"""
Migration: Add forum chat fields to ChatRoom model.

This migration extends ChatRoom with:
- enrollment ForeignKey to SubjectEnrollment (forum student-teacher chats)
- New chat types: FORUM_SUBJECT, FORUM_TUTOR
- Database indexes for query optimization

PostgreSQL Compatibility: CONFIRMED
- ForeignKey with CASCADE: Compatible with PostgreSQL and SQLite
- Index creation: Compatible with both databases
- CharField choices: Compatible with both databases
- No PostgreSQL-specific SQL used

Safe for:
- SQLite (development/test)
- PostgreSQL (production via Supabase)
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0014_add_subscription_expires_at"),
        ("chat", "0003_chatroom_auto_delete_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Связь с зачислением студента на предмет (для forum_subject типа)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_chats",
                to="materials.subjectenrollment",
                verbose_name="Зачисление на предмет",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                choices=[
                    ("direct", "Личный чат"),
                    ("group", "Групповой чат"),
                    ("support", "Поддержка"),
                    ("class", "Класс"),
                    ("general", "Общий форум"),
                    ("forum_subject", "Форум по предмету"),
                    ("forum_tutor", "Форум с тьютором"),
                ],
                default="direct",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["type", "enrollment"], name="chat_type_enrollment_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["type", "is_active"], name="chat_type_active_idx"
            ),
        ),
    ]
