# Generated by Django 5.2.8 on 2025-12-06 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_add_forum_chat_fields"),
    ]

    operations = [
        # Migration skipped - constraints handled in application code
    ]
