# Generated by Django 6.0 on 2025-12-27 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_add_optimization_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chatroom_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chatroom_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chatroom_enrollment_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_room_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_sender_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_thread_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_type_idx",
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время удаления"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["is_deleted"], name="message_deleted_idx"),
        ),
    ]
