# Generated by Django 4.2.7 on 2025-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_remove_chatroom_chatroom_created_by_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="Содержание"),
        ),
    ]
