# Generated by Django 4.2.7 on 2025-12-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_allow_blank_message_content"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "is_deleted"], name="message_room_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at"], name="message_room_created_idx"
            ),
        ),
    ]
