# Generated by Django 4.2.7 on 2026-01-01 14:04
"""
Migration: Convert enrollment_id (BigIntegerField) to enrollment (ForeignKey).
Replaces the BigIntegerField with a proper ForeignKey to SubjectEnrollment.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_add_message_indexes"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="enrollment_id",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Зачисление студента на предмет (для forum_tutor/forum_subject типов)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_chats",
                to="materials.subjectenrollment",
                verbose_name="Зачисление на предмет",
            ),
        ),
    ]
