# Generated by Django 4.2.7 on 2026-01-01 14:04
"""
Migration: Convert enrollment_id (BigIntegerField) to enrollment (ForeignKey).
Modified to skip FK conversion due to circular dependency - keep as BigIntegerField.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_add_message_indexes"),
    ]

    operations = [
        # Placeholder - no operations needed
        # The enrollment_id field remains as is
    ]
