# Generated by Django 4.2.7 on 2026-01-01 14:04
"""
Migration: Convert enrollment_id (BigIntegerField) to enrollment (ForeignKey).

This migration:
1. Removes the unique constraint first (depends on enrollment)
2. Removes the index on enrollment_id
3. Drops enrollment_id column
4. Adds enrollment as ForeignKey
5. Re-adds the index and constraint

SQLite Compatibility: Uses SeparateDatabaseAndState to handle SQLite limitations
"""

from django.db import migrations, models
import django.db.models.deletion


def migrate_enrollment_data(apps, schema_editor):
    """
    Data migration: Copy enrollment_id values to new enrollment FK.
    Since we're replacing the field, data will be preserved via column rename.
    """
    pass  # SQLite will handle this automatically via column rename


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0033_remove_materialprogressaudittrail_progress_and_more"),
        ("chat", "0009_add_message_indexes"),
    ]

    operations = [
        # Step 1: Remove index (constraint may not exist if 0005 was not fully applied)
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chat_type_enrollment_idx",
        ),
        # Step 3: Rename BigIntegerField to temp name, then alter to FK
        # Using AlterField instead of Remove+Add to preserve data
        migrations.AlterField(
            model_name="chatroom",
            name="enrollment_id",
            field=models.ForeignKey(
                blank=True,
                db_column="enrollment_id",
                help_text="Зачисление студента на предмет (для forum_subject типа)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_chats",
                to="materials.subjectenrollment",
                verbose_name="Зачисление на предмет",
            ),
        ),
        # Step 4: Rename field from enrollment_id to enrollment
        migrations.RenameField(
            model_name="chatroom",
            old_name="enrollment_id",
            new_name="enrollment",
        ),
        # Step 5: Re-add index
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["type", "enrollment"], name="chat_type_enrollment_idx"
            ),
        ),
        # Step 6: Re-add constraint
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enrollment__isnull", False)),
                fields=("type", "enrollment"),
                name="unique_forum_per_enrollment",
            ),
        ),
    ]
