# Generated by Django 4.2.7 on 2026-01-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0037_subjectenrollment_status"),
        ("chat", "0009_add_message_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatroom",
            new_name="chat_type_enrollment_idx_v2",
            old_name="chat_type_enrollment_idx",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="enrollment_id",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                db_column="enrollment_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="materials.subjectenrollment",
                verbose_name="Запись на предмет",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("type", "enrollment"), name="unique_forum_per_enrollment"
            ),
        ),
    ]
