# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_convert_enrollment_to_fk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chat_type_enrollment_idx",
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["type", "enrollment"], name="chat_type_enrollment_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("type", "enrollment"), name="unique_forum_per_enrollment"
            ),
        ),
    ]
