# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_convert_enrollment_to_fk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chat_type_enrollment_idx",
        ),
    ]
