# Generated by Django 6.0 on 2026-01-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_convert_enrollment_to_fk'),
    ]

    operations = [
    ]
