# Generated by Django 6.0 on 2026-01-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_convert_enrollment_to_fk'),
        ('materials', '0033_remove_materialprogressaudittrail_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='Зачисление студента на предмет (для forum_subject типа)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_chats', to='materials.subjectenrollment', verbose_name='Зачисление на предмет'),
        ),
    ]
