# Generated by Django 4.2.7 on 2026-01-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0037_subjectenrollment_status"),
        ("chat", "0012_chatroom_enrollment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="chatroom",
                    name="enrollment",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="materials.subjectenrollment",
                        verbose_name="Запись на предмет",
                        db_column="enrollment_id",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
