# Generated by Django 4.2.7 on 2026-01-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_recreate_chat_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagethread",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="messagethread",
            name="room",
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("image", "Изображение"),
                    ("file", "Файл"),
                    ("system", "Системное"),
                ],
                default="text",
                max_length=20,
                verbose_name="Тип сообщения",
            ),
        ),
        migrations.DeleteModel(
            name="MessageRead",
        ),
        migrations.DeleteModel(
            name="MessageThread",
        ),
    ]
