# Generated by Django 4.2.7 on 2026-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0020_add_message_sender_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="idx_message_sender",
        ),
    ]
