# Generated by Django 4.2.7 on 2026-01-10 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0022_alter_chatparticipant_user_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="is_muted",
            field=models.BooleanField(default=False, verbose_name="Заглушен"),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
