// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sobptsqfzgycmauglqzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnB0c3Fmemd5Y21hdWdscXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMDYxNzEsImV4cCI6MjA3Njc4MjE3MX0.OTJTYuazN2AEbcFlnHrt5ux7w-syOB90lTx3FLT2s4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});