# Generated by Django 5.2.7 on 2025-10-26 08:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram ID')),
                ('applicant_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=20, verbose_name='Applicant Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Tracking Token')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Grade')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
                ('experience', models.TextField(blank=True, verbose_name='Experience')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation')),
                ('parent_first_name', models.CharField(blank=True, max_length=100, verbose_name='Parent First Name')),
                ('parent_last_name', models.CharField(blank=True, max_length=100, verbose_name='Parent Last Name')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Parent Email')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Parent Phone')),
                ('parent_telegram_id', models.CharField(blank=True, max_length=100, verbose_name='Parent Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('generated_username', models.CharField(blank=True, max_length=150, verbose_name='Generated Username')),
                ('generated_password', models.CharField(blank=True, max_length=128, verbose_name='Generated Password')),
                ('parent_username', models.CharField(blank=True, max_length=150, verbose_name='Parent Username')),
                ('parent_password', models.CharField(blank=True, max_length=128, verbose_name='Parent Password')),
                ('telegram_message_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Message ID')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
