# Generated by Django 4.2.7 on 2025-12-30 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="generated_password",
        ),
        migrations.RemoveField(
            model_name="application",
            name="parent_password",
        ),
    ]
