# Generated by Django 5.2.8 on 2025-11-25 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='pending', max_length=20, verbose_name='Статус')),
                ('lesson_topic', models.CharField(blank=True, max_length=255, verbose_name='Тема урока')),
                ('lesson_notes', models.TextField(blank=True, verbose_name='Заметки к уроку')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID события в Google Calendar')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_bookings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='materials.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-time_slot__date', '-time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='PachcaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255, verbose_name='API токен Pachca')),
                ('channel_id', models.CharField(max_length=100, verbose_name='ID канала для уведомлений')),
                ('notify_on_booking', models.BooleanField(default=True, verbose_name='Уведомлять о новых бронированиях')),
                ('notify_on_cancellation', models.BooleanField(default=True, verbose_name='Уведомлять об отменах')),
                ('notify_on_reschedule', models.BooleanField(default=True, verbose_name='Уведомлять о переносах')),
                ('notify_reminder_hours', models.IntegerField(default=24, verbose_name='Напоминание за N часов до урока')),
                ('is_active', models.BooleanField(default=True, verbose_name='Интеграция активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pachca_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Интеграция Pachca',
                'verbose_name_plural': 'Интеграции Pachca',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('slot_duration', models.IntegerField(choices=[(30, '30 минут'), (45, '45 минут'), (60, '60 минут'), (90, '90 минут')], default=60, verbose_name='Длительность урока (минут)')),
                ('max_students', models.IntegerField(default=1, verbose_name='Макс. количество студентов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, verbose_name='ID календаря Google')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(related_name='teacher_availabilities', to='materials.subject', verbose_name='Предметы')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон доступности',
                'verbose_name_plural': 'Шаблоны доступности',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('teacher', 'weekday', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('booked', 'Забронирован'), ('blocked', 'Заблокирован')], default='available', max_length=20, verbose_name='Статус')),
                ('current_students', models.IntegerField(default=0, verbose_name='Текущее количество студентов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='scheduling.teacheravailability')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('rescheduled', 'Перенесено'), ('no_show', 'Не явился')], max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scheduling.booking')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('new_time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_bookings_history', to='scheduling.timeslot')),
                ('old_time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_bookings_history', to='scheduling.timeslot')),
            ],
            options={
                'verbose_name': 'История бронирования',
                'verbose_name_plural': 'История бронирований',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'status'], name='scheduling__date_55f91f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['availability', 'date'], name='scheduling__availab_a54867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('availability', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', '-created_at'], name='scheduling__booking_0af7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'status'], name='scheduling__student_5b0300_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['teacher', 'status'], name='scheduling__teacher_b8a745_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['time_slot', 'status'], name='scheduling__time_sl_882d29_idx'),
        ),
    ]
