# Generated by Django 4.2.7 on 2026-01-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0008_add_postgresql_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lesson",
            name="scheduling_lesson_teacher_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="scheduling_lesson_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="scheduling_lesson_date_status_idx",
        ),
        migrations.AddField(
            model_name="lesson",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Lesson notes"),
        ),
    ]
