# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0009_add_lesson_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
