# Generated by Django 4.2.7 on 2026-01-07 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0010_delete_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
    ]
