# Generated by Django 4.2.7 on 2026-01-07 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0011_alter_lesson_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
    ]
