# Generated by Django 4.2.7 on 2026-01-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduling", "0013_add_date_index_and_optimize_queries"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lesson",
            new_name="scheduling__date_555ba9_idx",
            old_name="scheduling_lesson_date_idx",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taught_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "student", "date", "status"],
                name="scheduling__teacher_9bd4ad_idx",
            ),
        ),
    ]
