# Generated by Django 4.2.7 on 2026-01-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0014_fix_scheduling_issues"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lesson",
            name="scheduling__teacher_9bd4ad_idx",
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "date", "status"],
                name="scheduling__teacher_9f0f25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["student", "date", "status"],
                name="scheduling__student_ddf12a_idx",
            ),
        ),
    ]
