# Generated by Django 5.2.7 on 2025-10-23 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('instructions', models.TextField(verbose_name='Инструкции')),
                ('type', models.CharField(choices=[('homework', 'Домашнее задание'), ('test', 'Тест'), ('project', 'Проект'), ('essay', 'Эссе'), ('practical', 'Практическая работа')], default='homework', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('closed', 'Закрыто')], default='draft', max_length=20, verbose_name='Статус')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Максимальный балл')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Время выполнения в минутах', null=True, verbose_name='Временной лимит')),
                ('attempts_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит попыток')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('due_date', models.DateTimeField(verbose_name='Срок сдачи')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги')),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5')], default=1, verbose_name='Уровень сложности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один вариант'), ('multiple_choice', 'Несколько вариантов'), ('text', 'Текстовый ответ'), ('number', 'Числовой ответ')], default='single_choice', max_length=20, verbose_name='Тип вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты ответов')),
                ('correct_answer', models.JSONField(blank=True, default=dict, verbose_name='Правильный ответ')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Ответ')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('submitted', 'Сдано'), ('graded', 'Оценено'), ('returned', 'Возвращено на доработку')], default='submitted', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балл')),
                ('max_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('answer_choice', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Заработанные баллы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.assignmentquestion', verbose_name='Вопрос')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.assignmentsubmission', verbose_name='Ответ на задание')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
