# Generated by Django 4.2.7 on 2026-01-01 17:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0020_remove_assignment_assignment_due_date_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        help_text="Оценка от 0 до 10",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        help_text="Детальная обратная связь для студента",
                        verbose_name="Текст обратной связи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_feedback",
                        to="assignments.assignmentsubmission",
                        verbose_name="Ответ на задание",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь на ответ",
                "verbose_name_plural": "Обратная связь на ответы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "teacher"],
                        name="assignments_submiss_c71c20_idx",
                    ),
                    models.Index(
                        fields=["teacher", "-created_at"],
                        name="assignments_teacher_35cefe_idx",
                    ),
                ],
            },
        ),
    ]
