# Generated by Django 4.2.7 on 2026-01-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0021_add_submission_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="show_correct_answers",
            field=models.BooleanField(
                default=False,
                help_text="Разрешить студентам видеть правильные ответы после срока выполнения",
                verbose_name="Показать правильные ответы",
            ),
        ),
    ]
