# Generated by Django 5.2.7 on 2025-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_fio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
