# Generated by Django 5.2.7 on 2025-10-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_customer_fio_payment_service_name'),
    ]

    operations = [
        # Удаляем старые поля безопасно (проверяем существование через SQL)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE payments_payment DROP COLUMN IF EXISTS label;
                    ALTER TABLE payments_payment DROP COLUMN IF EXISTS operation_id;
                    ALTER TABLE payments_payment DROP COLUMN IF EXISTS payer;
                    ALTER TABLE payments_payment DROP COLUMN IF EXISTS raw;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='payment',
                    name='label',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='operation_id',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='payer',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='raw',
                ),
            ],
        ),
        
        # Добавляем новые поля
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='return_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        # Изменяем статусы
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_capture', 'Waiting for Capture'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]