# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_add_optimization_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_status_date_idx",
        ),
    ]
