# Generated by Django 4.2.7 on 2025-12-08 06:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0005_alter_payment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма счета в рублях",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text='Описание услуг (например: "Оплата за 4 занятия по математике")',
                        verbose_name="Описание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("viewed", "Просмотрен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                            ("overdue", "Просрочен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Дата, до которой должен быть оплачен счет",
                        verbose_name="Срок оплаты",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда счет был отправлен родителю",
                        null=True,
                        verbose_name="Дата отправки",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда родитель впервые просмотрел счет",
                        null=True,
                        verbose_name="Дата просмотра",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда счет был оплачен",
                        null=True,
                        verbose_name="Дата оплаты",
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        blank=True,
                        help_text="ID сообщения с уведомлением о счете в Telegram",
                        max_length=255,
                        null=True,
                        verbose_name="ID сообщения в Telegram",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="Автоматически берется из student.student_profile.parent",
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Родитель",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Связанный платеж YooKassa (заполняется при оплате)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="payments.payment",
                        verbose_name="Платеж",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"role": "tutor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тьютор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "Счета",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("viewed", "Просмотрен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                            ("overdue", "Просрочен"),
                        ],
                        max_length=20,
                        verbose_name="Старый статус",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("viewed", "Просмотрен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                            ("overdue", "Просрочен"),
                        ],
                        max_length=20,
                        verbose_name="Новый статус",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Опциональное пояснение причины изменения статуса",
                        null=True,
                        verbose_name="Причина изменения",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="invoices.invoice",
                        verbose_name="Счет",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса счета",
                "verbose_name_plural": "История статусов счетов",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "-changed_at"],
                        name="idx_history_invoice_date",
                    ),
                    models.Index(
                        fields=["changed_by", "-changed_at"],
                        name="idx_history_user_date",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tutor", "status"], name="idx_invoice_tutor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["parent", "status"], name="idx_invoice_parent_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "status"], name="idx_invoice_due_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "-created_at"], name="idx_invoice_student_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment"],
                name="idx_invoice_payment",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["telegram_message_id"],
                name="idx_invoice_telegram",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                models.Q(amount__gt=0), name="check_invoice_amount_positive"
            ),
        ),
    ]
