# Generated by Django 4.2.7 on 2025-12-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="idx_invoice_payment",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="idx_invoice_telegram",
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["payment"], name="idx_invoice_payment"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["telegram_message_id"], name="idx_invoice_telegram"
            ),
        ),
    ]
