# Generated by Django 4.2.7 on 2026-01-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_fix_partial_indexes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sent_at__isnull", True),
                    ("sent_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="check_invoice_sent_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("viewed_at__isnull", True),
                    ("sent_at__isnull", True),
                    ("viewed_at__gte", models.F("sent_at")),
                    _connector="OR",
                ),
                name="check_invoice_viewed_after_sent",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_at__isnull", True),
                    ("viewed_at__isnull", True),
                    ("paid_at__gte", models.F("viewed_at")),
                    _connector="OR",
                ),
                name="check_invoice_paid_after_viewed",
            ),
        ),
    ]
