# Generated by Django 4.2.7 on 2026-01-01 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_empty"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="check_invoice_amount_positive",
        ),
    ]
