# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0035_alter_subjectenrollment_unique_together_and_more"),
        ("invoices", "0005_fix_enrollment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Опционально: привязка к конкретному предмету",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="materials.subjectenrollment",
                verbose_name="Зачисление на предмет",
            ),
        ),
    ]
