# Generated by Django 4.2.7 on 2026-01-05 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0035_alter_subjectenrollment_unique_together_and_more"),
        ("invoices", "0005_fix_enrollment_reference"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE invoices_invoice
                ADD COLUMN enrollment_id BIGINT NULL REFERENCES materials_subjectenrollment(id) ON DELETE SET NULL;
                CREATE INDEX idx_invoice_enrollment ON invoices_invoice(enrollment_id);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_invoice_enrollment;
                ALTER TABLE invoices_invoice DROP COLUMN IF EXISTS enrollment_id;
            """,
        ),
    ]
