# Generated by Django 4.2.7 on 2026-01-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_fix_enrollment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Опционально: привязка к конкретному предмету",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="materials.SubjectEnrollment",
                verbose_name="Зачисление на предмет",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sent_at__isnull", True),
                    ("sent_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="check_invoice_sent_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("viewed_at__isnull", True),
                    ("sent_at__isnull", True),
                    ("viewed_at__gte", models.F("sent_at")),
                    _connector="OR",
                ),
                name="check_invoice_viewed_after_sent",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_at__isnull", True),
                    ("viewed_at__isnull", True),
                    ("paid_at__gte", models.F("viewed_at")),
                    _connector="OR",
                ),
                name="check_invoice_paid_after_viewed",
            ),
        ),
    ]
