# Generated by Django 5.2.8 on 2025-12-07 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField(default=0, verbose_name="Позиция X")),
                ("position_y", models.FloatField(default=0, verbose_name="Позиция Y")),
                (
                    "is_unlocked",
                    models.BooleanField(default=False, verbose_name="Разблокирован"),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время разблокировки"
                    ),
                ),
                (
                    "node_color",
                    models.CharField(
                        default="#4F46E5", max_length=7, verbose_name="Цвет узла"
                    ),
                ),
                (
                    "node_size",
                    models.IntegerField(default=50, verbose_name="Размер узла"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Урок в графе",
                "verbose_name_plural": "Уроки в графах",
                "ordering": ["graph", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("text_problem", "Текстовая задача"),
                            ("quick_question", "Быстрый вопрос"),
                            ("theory", "Теория"),
                            ("video", "Видео"),
                        ],
                        max_length=20,
                        verbose_name="Тип элемента",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="Структура зависит от типа элемента",
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Сложность (1-10)",
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Время выполнения (минуты)",
                    ),
                ),
                (
                    "max_score",
                    models.IntegerField(default=100, verbose_name="Максимальный балл"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Теги"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Доступен всем учителям"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_elements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент",
                "verbose_name_plural": "Элементы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ElementProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.JSONField(blank=True, null=True, verbose_name="Ответ"),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Баллы"),
                ),
                ("max_score", models.IntegerField(verbose_name="Максимальный балл")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("skipped", "Пропущен"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, verbose_name="Затрачено времени (секунды)"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, verbose_name="Количество попыток"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="knowledge_graph.element",
                        verbose_name="Элемент",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "graph_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_progress",
                        to="knowledge_graph.graphlesson",
                        verbose_name="Урок в графе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по элементу",
                "verbose_name_plural": "Прогресс по элементам",
                "ordering": ["graph_lesson", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "allow_skip",
                    models.BooleanField(
                        default=False, verbose_name="Разрешить пропуск уроков"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_graphs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создан учителем",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_graphs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_graphs",
                        to="materials.Subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Граф знаний",
                "verbose_name_plural": "Графы знаний",
                "ordering": ["student", "subject"],
            },
        ),
        migrations.AddField(
            model_name="graphlesson",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledge_graph.knowledgegraph",
                verbose_name="Граф",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название урока"),
                ),
                ("description", models.TextField(verbose_name="Описание урока")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Доступен всем учителям"
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.IntegerField(
                        default=0, verbose_name="Общая продолжительность (минуты)"
                    ),
                ),
                (
                    "total_max_score",
                    models.IntegerField(
                        default=0, verbose_name="Максимальный общий балл"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_lessons",
                        to="materials.Subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="lessons",
            field=models.ManyToManyField(
                related_name="graphs",
                through="knowledge_graph.GraphLesson",
                to="knowledge_graph.lesson",
                verbose_name="Уроки",
            ),
        ),
        migrations.AddField(
            model_name="graphlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledge_graph.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.CreateModel(
            name="LessonDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("required", "Обязательная"),
                            ("recommended", "Рекомендованная"),
                            ("optional", "Опциональная"),
                        ],
                        default="required",
                        max_length=20,
                        verbose_name="Тип зависимости",
                    ),
                ),
                (
                    "min_score_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Минимальный процент для разблокировки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="knowledge_graph.graphlesson",
                        verbose_name="Предыдущий урок",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="knowledge_graph.knowledgegraph",
                        verbose_name="Граф",
                    ),
                ),
                (
                    "to_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="knowledge_graph.graphlesson",
                        verbose_name="Следующий урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зависимость уроков",
                "verbose_name_plural": "Зависимости уроков",
                "ordering": ["graph", "from_lesson", "to_lesson"],
            },
        ),
        migrations.CreateModel(
            name="LessonElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Порядок в уроке")),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, verbose_name="Необязательный элемент"
                    ),
                ),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True, verbose_name="Дополнительные инструкции"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_graph.element",
                        verbose_name="Элемент",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_graph.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент урока",
                "verbose_name_plural": "Элементы уроков",
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="elements",
            field=models.ManyToManyField(
                related_name="lessons",
                through="knowledge_graph.LessonElement",
                to="knowledge_graph.element",
                verbose_name="Элементы",
            ),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("failed", "Не пройден"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "completed_elements",
                    models.IntegerField(default=0, verbose_name="Завершено элементов"),
                ),
                (
                    "total_elements",
                    models.IntegerField(default=0, verbose_name="Всего элементов"),
                ),
                (
                    "completion_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Процент завершения",
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(default=0, verbose_name="Общий балл"),
                ),
                (
                    "max_possible_score",
                    models.IntegerField(
                        default=0, verbose_name="Максимально возможный балл"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "total_time_spent_seconds",
                    models.IntegerField(
                        default=0, verbose_name="Общее время (секунды)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="knowledge_graph.graphlesson",
                        verbose_name="Урок в графе",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по уроку",
                "verbose_name_plural": "Прогресс по урокам",
                "ordering": ["student", "graph_lesson"],
            },
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(
                fields=["element_type"], name="knowledge_g_element_0bc5e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(
                fields=["created_by"], name="knowledge_g_created_ecd74b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(
                fields=["difficulty"], name="knowledge_g_difficu_895cd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(
                fields=["-created_at"], name="knowledge_g_created_3715e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="elementprogress",
            index=models.Index(
                fields=["student", "element"], name="knowledge_g_student_37cffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="elementprogress",
            index=models.Index(
                fields=["graph_lesson"], name="knowledge_g_graph_l_fc27a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="elementprogress",
            index=models.Index(fields=["status"], name="knowledge_g_status_b0c914_idx"),
        ),
        migrations.AddIndex(
            model_name="elementprogress",
            index=models.Index(
                fields=["-updated_at"], name="knowledge_g_updated_b39d24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="elementprogress",
            unique_together={("student", "element", "graph_lesson")},
        ),
        migrations.AddIndex(
            model_name="knowledgegraph",
            index=models.Index(
                fields=["student", "subject"], name="knowledge_g_student_75f63c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraph",
            index=models.Index(
                fields=["is_active"], name="knowledge_g_is_acti_e7442c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgegraph",
            unique_together={("student", "subject")},
        ),
        migrations.AddIndex(
            model_name="graphlesson",
            index=models.Index(
                fields=["graph", "lesson"], name="knowledge_g_graph_i_4b9905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphlesson",
            index=models.Index(
                fields=["is_unlocked"], name="knowledge_g_is_unlo_292a6a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="graphlesson",
            unique_together={("graph", "lesson")},
        ),
        migrations.AddIndex(
            model_name="lessondependency",
            index=models.Index(fields=["graph"], name="knowledge_g_graph_i_d1c32d_idx"),
        ),
        migrations.AddIndex(
            model_name="lessondependency",
            index=models.Index(
                fields=["from_lesson"], name="knowledge_g_from_le_91b0e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessondependency",
            index=models.Index(
                fields=["to_lesson"], name="knowledge_g_to_less_67f7eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessondependency",
            unique_together={("graph", "from_lesson", "to_lesson")},
        ),
        migrations.AddIndex(
            model_name="lessonelement",
            index=models.Index(
                fields=["lesson", "order"], name="knowledge_g_lesson__3f1231_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonelement",
            unique_together={("lesson", "element"), ("lesson", "order")},
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["subject"], name="knowledge_g_subject_abdc07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["created_by"], name="knowledge_g_created_ba1b41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["-created_at"], name="knowledge_g_created_04c8b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["student", "graph_lesson"],
                name="knowledge_g_student_788f6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(fields=["status"], name="knowledge_g_status_cd1931_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["-last_activity"], name="knowledge_g_last_ac_b43c23_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("student", "graph_lesson")},
        ),
    ]
