# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0003_add_optimization_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="element",
            name="element_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="element",
            name="element_is_public_idx",
        ),
        migrations.RemoveIndex(
            model_name="element",
            name="element_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="element",
            name="element_difficulty_idx",
        ),
        migrations.RemoveIndex(
            model_name="elementfile",
            name="elementfile_uploaded_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="elementfile",
            name="elementfile_element_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="elementprogress",
            name="elementprogress_student_element_idx",
        ),
        migrations.RemoveIndex(
            model_name="elementprogress",
            name="elementprogress_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="graphlesson",
            name="graphlesson_graph_idx",
        ),
    ]
