# Generated by Django 5.2.7 on 2025-10-26 09:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_subjectenrollment_subjectpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'zip', 'rar'])], verbose_name='Файл ответа')),
                ('submission_text', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('reviewed', 'Проверено'), ('returned', 'Возвращено на доработку')], default='submitted', max_length=20, verbose_name='Статус')),
                ('is_late', models.BooleanField(default=False, verbose_name='С опозданием')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='materials.material', verbose_name='Материал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на материал',
                'verbose_name_plural': 'Ответы на материалы',
                'ordering': ['-submitted_at'],
                'unique_together': {('material', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MaterialFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Текст фидбэка')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='materials.materialsubmission', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Фидбэк по материалу',
                'verbose_name_plural': 'Фидбэки по материалам',
                'ordering': ['-created_at'],
            },
        ),
    ]
