# Generated by Django 5.2.7 on 2025-10-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialsubmission_materialfeedback'),
    ]

    operations = [
    ]
