# Generated by Django 5.2.7 on 2025-10-29 07:38

import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_subjectenrollment_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectpayment',
            name='due_date',
            field=models.DateTimeField(default=materials.models.SubjectPayment._default_due_date, verbose_name='Срок оплаты'),
        ),
    ]
