# Generated by Django 5.2.7 on 2025-11-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_add_teachersubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectenrollment',
            unique_together={('student', 'subject', 'teacher')},
        ),
        migrations.CreateModel(
            name='SubjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('next_payment_date', models.DateTimeField(verbose_name='Дата следующего платежа')),
                ('payment_interval_weeks', models.PositiveIntegerField(default=1, verbose_name='Интервал платежей (недели)')),
                ('yookassa_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID подписки в ЮКассу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='materials.subjectenrollment', verbose_name='Зачисление')),
            ],
            options={
                'verbose_name': 'Подписка на предмет',
                'verbose_name_plural': 'Подписки на предметы',
                'ordering': ['-created_at'],
            },
        ),
    ]
