# Generated by Django 5.2.8 on 2025-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_merge_0004_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectenrollment',
            name='custom_subject_name',
            field=models.CharField(blank=True, help_text='Если указано, используется вместо стандартного названия предмета', max_length=200, null=True, verbose_name='Кастомное название предмета'),
        ),
        migrations.AlterField(
            model_name='subjectpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting_for_payment', 'Ожидание платежа'), ('paid', 'Оплачен'), ('expired', 'Просрочен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
