# Generated by Django 5.2.8 on 2025-11-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_studyplanfile'),
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectpayment',
            unique_together={('enrollment', 'payment')},
        ),
    ]
