# Generated by Django 5.2.8 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_alter_subjectpayment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения доступа'),
        ),
    ]
