# Generated by Django 5.2.8 on 2025-12-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0014_add_subscription_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlanGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        help_text="Содержит предмет, класс, тему, подтемы, цель, ограничения",
                        verbose_name="Параметры генерации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plan_generations",
                        to="materials.subjectenrollment",
                        verbose_name="Зачисление на предмет",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_study_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plan_generations",
                        to="materials.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plan_generations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Генерация учебного плана",
                "verbose_name_plural": "Генерации учебных планов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("problem_set", "Задачник"),
                            ("reference_guide", "Методичка"),
                            ("video_list", "Видео-подборка"),
                            ("weekly_plan", "Недельный план"),
                        ],
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="study_plans/generated/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает генерации"),
                            ("generating", "Генерируется"),
                            ("compiled", "Скомпилирован"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_files",
                        to="materials.studyplangeneration",
                        verbose_name="Запрос на генерацию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный файл",
                "verbose_name_plural": "Сгенерированные файлы",
                "ordering": ["generation", "file_type"],
            },
        ),
        migrations.AddIndex(
            model_name="studyplangeneration",
            index=models.Index(
                fields=["teacher", "created_at"], name="materials_s_teacher_81decd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplangeneration",
            index=models.Index(
                fields=["student", "subject"], name="materials_s_student_63eedf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplangeneration",
            index=models.Index(fields=["status"], name="materials_s_status_98447a_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedfile",
            index=models.Index(
                fields=["generation", "status"], name="materials_g_generat_2e8978_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedfile",
            unique_together={("generation", "file_type")},
        ),
    ]
