# Generated by Django 5.2.8 on 2025-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0015_add_study_plan_generation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyplangeneration",
            name="progress_message",
            field=models.CharField(
                blank=True,
                help_text='Отображается во время генерации (например, "Генерация задачника...")',
                max_length=255,
                null=True,
                verbose_name="Сообщение о прогрессе",
            ),
        ),
    ]
