# Generated by Django 4.2.7 on 2025-12-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0020_add_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(db_index=True, max_length=200, verbose_name="Поисковый запрос")),
                ("results_count", models.PositiveIntegerField(default=0, verbose_name="Количество результатов")),
                ("used_filters", models.JSONField(default=dict, verbose_name="Использованные фильтры")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата поиска")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="material_searches", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "История поиска",
                "verbose_name_plural": "Истории поиска",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["user", "-created_at"], name="searchhist_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["-created_at"], name="searchhist_date_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["query"], name="searchhist_query_idx"),
        ),
    ]
