# Generated by Django 4.2.7 on 2025-12-27 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0026_material_comment_threading"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="User-Agent браузера"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байты)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата и время загрузки",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логирование загрузки материала",
                "verbose_name_plural": "Логирования загрузок материалов",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["material", "timestamp"], name="mat_dl_material_ts_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"], name="mat_dl_user_ts_idx"
                    ),
                    models.Index(
                        fields=["material", "user", "-timestamp"],
                        name="mat_dl_mat_user_ts_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"], name="mat_dl_ip_ts_idx"
                    ),
                ],
            },
        ),
    ]
