# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0032_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialprogressaudittrail",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="searchhistory",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="materialdownloadlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Лог загрузки материала",
                "verbose_name_plural": "Логи загрузок материалов",
            },
        ),
        migrations.RemoveIndex(
            model_name="material",
            name="material_subject_idx",
        ),
        migrations.RemoveIndex(
            model_name="material",
            name="material_author_idx",
        ),
        migrations.RemoveIndex(
            model_name="material",
            name="material_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="material",
            name="material_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="material",
            name="material_subject_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialdownloadlog",
            name="download_log_timestamp_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialdownloadlog",
            name="download_log_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialprogress",
            name="material_progress_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialprogress",
            name="material_progress_student_material_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialsubmission",
            name="material_submission_material_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialsubmission",
            name="material_submission_student_material_idx",
        ),
        migrations.RemoveIndex(
            model_name="materialsubmission",
            name="material_submission_submitted_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="subjectenrollment",
            name="subject_enrollment_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="subjectenrollment",
            name="subject_enrollment_subject_student_idx",
        ),
        migrations.RemoveIndex(
            model_name="subjectenrollment",
            name="subject_enrollment_teacher_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkassignmentauditlog",
            new_name="materials_b_perform_f56cc4_idx",
            old_name="materials_bu_perform_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkassignmentauditlog",
            new_name="materials_b_operati_59ae78_idx",
            old_name="materials_bu_operati_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkassignmentauditlog",
            new_name="materials_b_status_e036a2_idx",
            old_name="materials_bu_status_idx",
        ),
        migrations.RenameIndex(
            model_name="materialdownloadlog",
            new_name="materials_m_materia_5e3437_idx",
            old_name="mat_dl_material_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="materialdownloadlog",
            new_name="materials_m_user_id_30916e_idx",
            old_name="mat_dl_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="materialdownloadlog",
            new_name="materials_m_materia_56d976_idx",
            old_name="mat_dl_mat_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="materialdownloadlog",
            new_name="materials_m_ip_addr_3042f4_idx",
            old_name="mat_dl_ip_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="submissionfile",
            new_name="materials_s_submiss_191dc6_idx",
            old_name="materials_s_submiss_idx",
        ),
        migrations.RenameIndex(
            model_name="submissionfile",
            new_name="materials_s_file_ch_8e6204_idx",
            old_name="materials_s_file_ch_idx",
        ),
        migrations.AddField(
            model_name="subjectsubscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата истечения доступа"
            ),
        ),
        migrations.AlterField(
            model_name="materialdownloadlog",
            name="file_size",
            field=models.BigIntegerField(
                default=0, verbose_name="Размер файла (байты)"
            ),
        ),
        migrations.AlterField(
            model_name="materialdownloadlog",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP адрес"),
        ),
        migrations.AlterField(
            model_name="materialdownloadlog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время загрузки"
            ),
        ),
        migrations.AlterField(
            model_name="materialdownloadlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_downloads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="materialdownloadlog",
            name="user_agent",
            field=models.TextField(verbose_name="User-Agent браузера"),
        ),
        migrations.DeleteModel(
            name="MaterialProgressAuditTrail",
        ),
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
