# Generated by Django 4.2.7 on 2026-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0034_remove_materialprogressaudittrail_progress_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subjectenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student", "subject"),
                name="unique_active_enrollment_per_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "teacher"),
                name="unique_student_subject_teacher",
            ),
        ),
    ]
