# Generated by Django 4.2.7 on 2026-01-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0036_add_material_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                ],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
