# Generated by Django 5.2.8 on 2025-12-08 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="failedtask",
            new_name="core_failed_task_na_0a7b09_idx",
            old_name="core_failed_task_na_6c8b65_idx",
        ),
        migrations.RenameIndex(
            model_name="failedtask",
            new_name="core_failed_failed__3bd4c6_idx",
            old_name="core_failed_failed__a3e6b8_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecutionlog",
            new_name="core_task_e_task_na_b077ae_idx",
            old_name="core_task_e_task_na_eb8f45_idx",
        ),
    ]
