# Generated by Django 4.2.7 on 2025-12-28 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_configuration"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_audit__user_id_66db5a_idx",
            old_name="core_audit_log_user_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_audit__action_1cc579_idx",
            old_name="core_audit_log_action_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_audit__ip_addr_f0c0f7_idx",
            old_name="core_audit_log_ip_address_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_audit__target__fd0ddd_idx",
            old_name="core_audit_log_target_type_target_id_idx",
        ),
        migrations.RenameIndex(
            model_name="configuration",
            new_name="core_config_group_a0a722_idx",
            old_name="core_configu_group_key_idx",
        ),
        migrations.RenameIndex(
            model_name="configuration",
            new_name="core_config_updated_166918_idx",
            old_name="core_configu_updated_idx",
        ),
    ]
